services:
  - type: web
    name: ai-message-triage
    env: python
    buildCommand: "pip install -r requirements.txt && python train.py"
    startCommand: "uvicorn app:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
